name: Merge release
run-name: ff-only merge into a release branch
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source branch'
        required: true
        default: 'develop'
        type: choice
        options:
        - develop
        - qa
      target:
        description: 'Target branch'
        required: true
        default: 'qa'
        type: choice
        options:
        - devrelease
        - main
        - qa
        - release
jobs:
  ff-only-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target }}
          fetch-depth: 0
      - run: |
          echo 'Merging ${{ inputs.source }} into ${{ inputs.target }}'
          git merge --ff-only origin/${{ inputs.source }}
          git push
